language: node_js
node_js:
  - "4"
  - "5"
before_install:
  - npm install -g npm 
before_script:
  - npm install -g jshint 
  - npm install -g mocha 
  - npm install -g istanbul
  - npm install
script: 
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
