language: node_js
node_js:
  - "4"
  - "5"
before_install:
  - npm install -g npm 
before_script:
  - npm install -g jshint 
  - npm install -g mocha 
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
  - npm install
script: 
  - npm run lint
  - npm test
  - npm run coverage
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < coverage/lcov.info
