language: node_js
node_js:
- '4'
- '5'
before_install:
- npm install -g npm
before_script:
- npm install -g jshint
- npm install -g mocha
- npm install -g istanbul
- npm install -g codeclimate-test-reporter
- npm install
script:
- npm run lint
- npm test
- npm run coverage
after_success:
- npm run coveralls
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: florian.sey@gmail.com
  api_key:
    secure: iWolomthoCeHM3GIPw7CiXM8m1ZTDGjzbc/OmgjIn6LFp4Mt96m9IUynaVSP7lmsI2JR+CZgB4D+BLhOxxe4p5u7PO162VErX+Hn9NtqelcguPxY55Jkc8+Wn0e1s0j+TyGgV0ocTRyUcuF8X5Lw5xn9wTyLpfT/HPfoyx9ofWdWpVKNev/7/bFwGZ6wKbcRImqnAHQ21r1N6gkywIkXVL2CJPDfyhTNYzC+LEpEd4rGM928QVNDWFS+EnfpQTjmKlLncjEpdAAKqpI4kaoiFNo4HG061mS0jbPVr3KvqrLkd40BlB3NxfyQCEgTCI7lg9ZdOOInree8m3Xplnnq6dB02VN6XgMxNqIfrlJBR008lhp75qO3HboAno48GN6J6+h8v3m8UHSRSbzmC2GuSafFNmcKppSuqKPaQAdYNnxoJpRVOpB0RBgOWU9dl3lHQGsryCagxsaw7q1urUsUMfcApGe0whCuy9U3aUj8g0DOJSl+IhIeV0ZuJKDpsVMoFtWEYROJY6UyyUlgjBuaKQu5VRJn43OTDXY0oZz4orzv7Yv9A/AyE44pFKglb6mjomlRLPAuUPGgxG2LiY7dDzZW5SVjZs9STmuHGLXt1nnzkVZBpADdFMNaFtLjDTnUxxuil/cuD4BtVPjAySOnuUTQv5Skn7bd+l8Sl0UylhI=
  on:
    tags: true
    repo: seventy-three/validate-json-locales
